"""Record what the Python path filter does, so the TypeScript port can be held to it.

`glob_to_regex` exists to agree with `PurePosixPath.match` exactly, and the
translation is subtle enough -- right-anchored matching, `**` spanning one
segment, `re.escape`'s idiosyncratic character set -- that reimplementing the
oracle in TypeScript would only test the reimplementation. So this writes down
both halves: the regex Python emits for every pattern, character for character,
and the ground-truth match for every pattern against every corpus path.

Run it from the repository root after touching either implementation:

    uv run python ts/packages/server/scripts/write_path_filter_parity.py

The corpus and the pattern list are lifted from `tests/test_path_filter.py`; keep
them in step with it, because that suite is what proves the Python side of the
fixture is right in the first place.
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path, PurePosixPath

sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "src"))

from code_indexing_mcp.path_filter import glob_to_regex, path_condition

PATTERNS = [
    "*.py",
    "**/*.py",
    "src/**",
    "src/*",
    "**",
    "*",
    "a.py",
    "?.py",
    "[st]*/*.py",
    "[!s]*/*.py",
    "src/*/x.py",
    "**/**/*.py",
    "deep/**/*.py",
    "*_score.py",
    "50%off.py",
    "*.PY",
    "src/a.py",
    "**/deep/*",
    "*/*/*.py",
    "under_score.py",
    "my-file.py",
    "a+b.py",
    "f(x).py",
    "with space.py",
    "d$e.py",
    "g{1}.py",
    # PurePosixPath normalizes these before matching.
    "*/",
    "foo//bar",
    "./a.py",
    "a/./b.py",
    "it's.py",
    "tab\there.py",
    "hash#tag.py",
    "amp&and.py",
    "tilde~x.py",
    "[]]*.py",
    "[!]]*.py",
]

# Translation must refuse these rather than emit a predicate that could be
# narrower than the post-filter.
UNTRANSLATABLE = ["", "/absolute/x.py", "[abc", "*[]", "*[!]", "*[a-]", "*[a\\\\]"]

CONDITIONS = [
    ["rare/*", "tests/*"],
    ["src/*", "/absolute"],
    [],
    ["it's.py"],
    ["*.py"],
]


def corpus() -> list[str]:
    segments = [
        "a",
        "b",
        "src",
        "deep",
        "tests",
        "x.py",
        "a.py",
        "b.pyi",
        "under_score.py",
        "50%off.py",
        "A.PY",
        "my-file.py",
        "with space.py",
    ]
    generator = random.Random(0)
    paths = set()
    for depth in (1, 2, 3, 4):
        for _ in range(400):
            paths.add("/".join(generator.choice(segments) for _ in range(depth)))
    return sorted(paths)


def main() -> None:
    paths = corpus()
    payload = {
        "note": "Generated by ts/packages/server/scripts/write_path_filter_parity.py.",
        "paths": paths,
        "patterns": [
            {
                "pattern": pattern,
                "regex": glob_to_regex(pattern),
                # One character per corpus path: "1" matched, "0" did not. A list
                # of booleans would be twenty times the size for the same content.
                "matches": "".join(
                    "1" if PurePosixPath(path).match(pattern) else "0" for path in paths
                ),
            }
            for pattern in PATTERNS
        ],
        "untranslatable": UNTRANSLATABLE,
        "conditions": [
            {"patterns": patterns, "condition": path_condition(patterns)} for patterns in CONDITIONS
        ],
    }
    destination = Path(__file__).resolve().parents[1] / "test" / "fixtures" / "path-filter.json"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {destination} ({len(paths)} paths, {len(PATTERNS)} patterns)")


if __name__ == "__main__":
    main()
