"""Record the Python MCP tool schemas, so the TypeScript port can be held to them.

The migration plan (§8) requires the TS server to reproduce the 16-tool JSON
schemas exactly -- field names, optionality, types, bounds, enum values, and
descriptions. Asserting that against hand-written expectations would only test
the reimplementation, so this writes down what the Python FastMCP surface
actually emits.

Two generator idioms are deliberately stripped while capturing, because they
are artifacts of the schema generator rather than the contract:

- pydantic's ``title`` keys on the object and on every property (FastMCP
  derives them from argument names; the tool-level ``title`` stays);
- the four-hint ``annotations`` keep only the hints themselves, normalized.

Everything else is kept verbatim. The TS test strips zod's equivalents
(``$schema``, ``additionalProperties``) before comparing, and key order is
irrelevant to the comparison.

Run it from the repository root after touching either implementation:

    uv run python ts/packages/server/scripts/write_tool_schema_parity.py
"""

from __future__ import annotations

import asyncio
import json
import sys
import tempfile
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "src"))

from code_indexing_mcp.application import Application, RuntimePaths
from code_indexing_mcp.server import create_server

HINTS = ("readOnlyHint", "destructiveHint", "idempotentHint", "openWorldHint")


class TinyEmbedder:
    model_id = "test/tiny"
    dimension = 4

    def embed_passages(self, texts: list[str]) -> list[list[float]]:
        return [[1.0, 0.0, 0.0, float(len(text))] for text in texts]

    def embed_query(self, text: str) -> list[float]:
        return [1.0, 0.0, 0.0, float(len(text))]


def strip_titles(schema: Any) -> Any:
    """Drop pydantic's generated ``title`` keys at every level of a schema."""

    if isinstance(schema, dict):
        return {key: strip_titles(value) for key, value in schema.items() if key != "title"}
    if isinstance(schema, list):
        return [strip_titles(item) for item in schema]
    return schema


async def main() -> None:
    with tempfile.TemporaryDirectory() as temporary:
        root = Path(temporary)
        app = Application(
            RuntimePaths(data=root / "data", cache=root / "cache"),
            embedder=TinyEmbedder(),
            cwd=root,
        )
        server = create_server(app)
        tools = await server.list_tools()
    payload = {
        "note": "Generated by ts/packages/server/scripts/write_tool_schema_parity.py.",
        "tools": [
            {
                "name": tool.name,
                "title": tool.title,
                "description": tool.description,
                "annotations": (
                    {hint: tool.annotations.model_dump()[hint] for hint in HINTS}
                    if tool.annotations is not None
                    else None
                ),
                "inputSchema": strip_titles(tool.inputSchema),
            }
            for tool in sorted(tools, key=lambda tool: tool.name)
        ],
    }
    destination = Path(__file__).resolve().parents[1] / "test" / "fixtures" / "tool-schemas.json"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {destination} ({len(tools)} tools)")


if __name__ == "__main__":
    asyncio.run(main())
